from __future__ import annotations

import json
import time
from pathlib import Path
import yaml

from .adapters.mock import MockAdapter
from .state import mark_stage, load_state, save_state


def reproduce_case(case_dir: Path, adapter_name: str = "mock") -> None:
    if adapter_name != "mock":
        raise ValueError("v0.1 ships only the non-empirical mock adapter")
    workflow = yaml.safe_load((case_dir / "WORKFLOW.yaml").read_text(encoding="utf-8"))
    adapter = MockAdapter()
    result = adapter.run(str(case_dir), workflow)
    out_dir = case_dir / "reproduction"
    out_dir.mkdir(exist_ok=True)
    runs_path = out_dir / "runs.json"
    payload = {"version": "0.1", "runs": [{"id": f"run-{int(time.time())}", "adapter": adapter.name, **result}]}
    runs_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    (out_dir / "comparison.md").write_text("# Comparison\n\nNo empirical artifact was generated by the mock adapter. Status remains `unverified`.\n", encoding="utf-8")
    state = load_state(case_dir)
    state["reproduction_status"] = "unverified"
    save_state(case_dir, state)
    mark_stage(case_dir, "reproduce", ["reproduction/runs.json", "reproduction/comparison.md"], "validate")
